locale = "en"
label = "English"
weight = 1
title = "Michal Dev Blog"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/shipthecode_logo_high_res.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Michał Duziak"
  email = ""
  headline = "Senior Unity Developer"
  bio = "Writing about game development, Unity architecture and shipping AAA games."
  links = [
    { linkedin = "https://www.linkedin.com/in/micha%C5%82-duziak-09a588120/" },
    { github = "https://github.com/Seremonik" },
  ]