# -- Main Menu --

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Seremonik"
  weight = 30

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/micha%C5%82-duziak-09a588120/"
  weight = 40

# -- Footer Menu --

[[footer]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 20

[[footer]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Seremonik"
  weight = 30

[[footer]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/micha%C5%82-duziak-09a588120/"
  weight = 40
